name: Docker Build & Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 891377317462.dkr.ecr.ap-south-1.amazonaws.com
  BACKEND_REPO: the-v-s-backend
  FRONTEND_REPO: the-v-s-frontend

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        run: |
          docker build -t $ECR_REGISTRY/$BACKEND_REPO:latest ./backend
          docker push $ECR_REGISTRY/$BACKEND_REPO:latest

      - name: Build and push frontend image
        run: |
          docker build -t $ECR_REGISTRY/$FRONTEND_REPO:latest ./frontend
          docker push $ECR_REGISTRY/$FRONTEND_REPO:latest
